name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
       image: mrvivekyadavggn/testapp
       tags: latest
       registry: docker.io
       dockerfile: Dockerfile.ci
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
